baseURL = "https://cmpsoares.com"
publishDir = "docs"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# theme
theme = "LoveIt"
# themes directory
# themesDir = "themes/LoveIt"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

[languages]
  [languages.en]
    weight = 1
    # language code
    languageCode = "en"
    # website title
    title = "CMPSOARES"
    # language name
    languageName = "English"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = false
    # default amount of posts in each pages
    paginate = 12
    # [UA-XXXXXXXX-X] google analytics code
    googleAnalytics = "UA-137270540-1"
    # copyright description used only for seo schema
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # date format
    dateFormatToUse = "2006-01-02"
    # Menu Info
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        # you can add extra information before the name (HTML format is allowed), such as icons
        pre = ""
        name = "Posts"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "about"
        pre = ""
        name = "About Me"
        url = "/about/"
        title = ""
        weight = 4
      [[languages.en.menu.main]]
        identifier = "contact"
        pre = ""
        name = "Contact Me"
        url = "/contact/"
        title = ""
        weight = 5
      [[languages.en.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        name = ""
        url = "https://github.com/cmpsoares91/cmpsoares.com"
        title = "GitHub"
        weight = 6
      [languages.en.params]
        # site description
        description = "Carlos Soares' personal website and blog"
        # site keywords
        keywords = ["carlos", "soares", "cmpsoares", "blog", "developer", "personal", "devops", "sre", "site reliability", "engineer", "go", "terraform", "automation", "monitoring", "obsevability", "analytics", "automation", "big data", "distributed", "datahub", "microservice", "architecture", "docker", "kafka", "elasticsearch", "cassandra", "python", "nodejs", "java", "innovation", "artificial intelligence", "cryptocurrencies", "blockchain", "startup", "agile", "scrum", "kanban", "scrumban"]
        # site default theme ("light", "dark", "auto")
        defaultTheme = "auto"
        # Home Page Info
        [languages.en.params.home]
          # Home Page Profile
          [languages.en.params.home.profile]
            enable = true
            # Gravatar Email for preferred avatar in home page
            # gravatarEmail = ""
            # URL of avatar shown in home page
            avatarURL = "/images/avatar.png"
            # subtitle shown in home page
            subtitle = "Curious Automation Hacker & Versatile Site Reliability and Big Data Engineer"
            # whether to use typeit animation for subtitle
            typeit = true
            # whether to show social links
            social = true
          # Home Page Posts
          [languages.en.params.home.posts]
            enable = true
            # special amount of posts in each home posts page
            paginate = 6
            # default behavior when you don't set "hiddenFromHomePage" in front matter
            defaultHiddenFromHomePage = false
        # Social Info in home page
        [languages.en.params.social]
          GitHub = "cmpsoares91"
          Linkedin = "cmpsoares"
          Twitter = "cmpsoares"
          # Instagram = "xxxx"
          Email = "contact@cmpsoares.com"
          # Facebook = "xxxx"
          Telegram = "cmpsoares"
          Medium = "@cmpsoares"
          Gitlab = "cmpsoares91"
          # Youtubelegacy = "xxxx"
          # Youtubecustom = "xxxx"
          # Youtubechannel = "xxxx"
          # Tumblr ="xxxx"
          Quora = "Carlos-Soares-2"
          # Keybase = "xxxx"
          # Pinterest = "xxxx"
          # Reddit = "xxxx"
          # Codepen = "xxxx"
          # FreeCodeCamp = "xxxx"
          # Bitbucket = "xxxx"
          Stackoverflow = "3555155"
          # Weibo = "xxxx"
          # Odnoklassniki = "xxxx"
          # VK = "xxxx"
          # Flickr = "xxxx"
          # Xing = "xxxx"
          # Snapchat = "xxxx"
          # Soundcloud = "xxxx"
          # Spotify = "xxxx"
          # Bandcamp = "xxxx"
          # Paypal = "cmpsoares"
          # Fivehundredpx = "xxxx"
          # Mix = "xxxx"
          # Goodreads = "xxxx"
          # Lastfm = "xxxx"
          # Foursquare = "xxxx"
          # Hackernews = "xxxx"
          # Kickstarter = "xxxx"
          # Patreon = "xxxx"
          # Steam = "xxxx"
          # Twitch = "xxxx"
          # Strava = "xxxx"
          # Skype = "xxxx"
          # Whatsapp = "xxxx"
          # Zhihu = "xxxx"
          # Douban = "xxxx"
          # Angellist = "xxxx"
          # Slidershare = "xxxx"
          # Jsfiddle = "xxxx"
          # Deviantart = "xxxx"
          # Behance = "xxxx"
          # Dribble = "xxxx"
          # Wordpress = "xxxx"
          # Vine = "xxxx"
          # Googlescholar = "xxxx"
          # Researchgate = "xxxx"
          # Mastodon = "xxxx"
          # MastodonPrefix = "https://mastodon.technology/"
          # Thingiverse = "xxxx"
          # Devto = "xxxx"
          # Gitea = "xxxx"
          # XMPP = "xxxx"
          # Matrix = "xxxx"
          # Bilibili = "xxxx"
        # Social Share Links in post page
        [languages.en.params.share]
          enable = true
          Twitter = true
          Facebook = true
          Linkedin = true
          Whatsapp = true
          Pinterest = true
          Tumblr = true
          HackerNews = true
          Reddit = true
          # VK = true
          Buffer = true
          # Xing = true
          # Line = true
          # Instapaper = true
          Pocket = true
          Digg = true
          Stumbleupon = true
          Flipboard = true
          Weibo = true
          # Renren = true
          # Myspace = true
          Blogger = true
          # Baidu = true
          # Odnoklassniki = true
          Evernote = true
          Skype = true
          Trello = true
          Mix = true
        # Comment Config
        [languages.en.params.comment]
          enable = true
          # Disqus Comment Config (https://disqus.com/)
          [languages.en.params.comment.disqus]
            # Disqus shortname to use Disqus in posts
            enable = true
            shortname = "cmpsoares"

[params]
  # LoveIt theme version
  version = "0.1.X"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/cmpsoares91/cmpsoares.com"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # Header info
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "auto"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
  # Footer Copyright Info
  [params.footer]
    # Site creation time
    since = 2019
    # ICP info only in China (HTML format is allowed)
    icp = ""
    # license info (HTML format is allowed)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # Page config
  [params.page]
    # whether to use lightgallery in the page
    lightgallery = true
    # whether to show link to Raw Markdown content of the post
    linkToMarkdown = true
  # mathematical formulas (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # Publisher Info just for SEO
  [params.publisher]
    name = "Carlos Manuel Soares"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40
  # Website Log Info just for SEO
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40
  # Website Image Info just for SEO
  [params.image]
    url = "cover.png"
    width = 800
    height = 600
  # CSS and JS Files CDN
  [params.cdn]
    # fontawesome-free@5.12.1 https://fontawesome.com/
    fontawesomeFreeCSS = ''
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = ''
    # smooth-scroll@16.1.2 https://github.com/cferdinandi/smooth-scroll
    smoothScrollJS = ''
    # sharer@0.4.0 https://github.com/ellisonleao/sharer.js
    sharerJS = ''
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    lazysizesJS = ''
    # lightgallery@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = ''
    lightgalleryJS = ''
    lightgalleryThumbnailJS = ''
    lightgalleryZoomJS = ''
    # typeit@6.5.1 https://github.com/alexmacarthur/typeit
    typeitJS = ''
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    # mermaid@8.4.8 https://github.com/knsv/mermaid
    mermaidJS = ''
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    aplayerCSS = ''
    aplayerJS = ''
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    metingJS = ''
    # echarts@4.6.0 https://echarts.apache.org/
    echartsJS = ''
    echartsMacaronsJS = ''
    # gitalk@1.6.2 https://github.com/gitalk/gitalk
    gitalkCSS = ''
    gitalkJS = ''
    # valine@1.3.10 https://valine.js.org/
    valineJS = ''
  # Advertisement Parameters (cmpsoares.com specific customization)
  [params.ads]
    [params.ads.adsense]
      client = "ca-pub-9080200840721283"
      inArticleSlot = "9080200840721283"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "Carlos Manuel Soares"
  link = "https://cmpsoares.com/"

# Sitemap Info
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":year/:month/:filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    useSessionStorage = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
